<?php
include '../components/bootstrap.php';
include 'root.php';
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Payouts | AMSOIL Championship Off-Road</title>
  <link rel="stylesheet" href="<?php echo $path ?>
css\global-style.css">
</head>

<body>
  <?php include '../components/header.php'; ?>
  <div class="container-fluid mt-5" id="media-container">
    <div class="row d-flex justify-content-center" style="overflow-x: clip;">
      <img src="<?php echo $path ?>bg/HEADER-org.jpg" class="img-zoom ">
      <h2 class="position-absolute mt-5 text-white">RESULTS</h2>
    </div>
  </div>
  <div class="container mt-5">
    <div class="row text-white payout-table">
      <p>All entries are subject to a $25 dollar admin fee + 10% service fee that covers taxes, etc. An additional 10% is allocated to the year-end payout. Below is a chart that outlines the breakdown of the remaining balance.</p>
      <p class="mb-4">Payout in all classes except kids classes 170, 570, and Short Course Kart</p>
      <table class="text-white text-center">
         <tbody>
            <tr>
               <td>&nbsp;</td>
               <td>
                  <p>Pay to 3rd</p>
               </td>
               <td>
                  <p>Pay to 4th</p>
               </td>
               <td>
                  <p>Pay to 5th</p>
               </td>
               <td>
                  <p>Pay to 6th</p>
               </td>
               <td>
                  <p>Pay to 8th</p>
               </td>
               <td>
                  <p>Pay to 9th</p>
               </td>
               <td>
                  <p>Pay to 10th</p>
               </td>
               <td>
                  <p>Pay to 11th</p>
               </td>
               <td>
                  <p>Pay to 12th</p>
               </td>
               <td>
                  <p>Pay to 13th</p>
               </td>
            </tr>
            <tr>
               <td>&nbsp;</td>
               <td>
                  <p>Up to 8 <br>Entries</p>
               </td>
               <td>
                  <p>9-10 <br>Entries</p>
               </td>
               <td>
                  <p>11-12 <br>Entries</p>
               </td>
               <td>
                  <p>13-14 <br>Entries</p>
               </td>
               <td>
                  <p>15-16 <br>Entries</p>
               </td>
               <td>
                  <p>17-18 <br>Entries</p>
               </td>
               <td>
                  <p>19-24 <br>Entries</p>
               </td>
               <td>
                  <p>25-29 <br>Entries</p>
               </td>
               <td>
                  <p>30-35 <br>Entries</p>
               </td>
               <td>
                  <p>36+ <br>Entries</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>1st</p>
               </td>
               <td>
                  <p>46.0%</p>
               </td>
               <td>
                  <p>42.0%</p>
               </td>
               <td>
                  <p>36.0%</p>
               </td>
               <td>
                  <p>32.5%</p>
               </td>
               <td>
                  <p>30.0%</p>
               </td>
               <td>
                  <p>30.0%</p>
               </td>
               <td>
                  <p>29.5%</p>
               </td>
               <td>
                  <p>27.0%</p>
               </td>
               <td>
                  <p>25.0%</p>
               </td>
               <td>
                  <p>24.0%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>2nd</p>
               </td>
               <td>
                  <p>31.0%</p>
               </td>
               <td>
                  <p>28.0%</p>
               </td>
               <td>
                  <p>25.0%</p>
               </td>
               <td>
                  <p>22.0%</p>
               </td>
               <td>
                  <p>20.0%</p>
               </td>
               <td>
                  <p>19.0%</p>
               </td>
               <td>
                  <p>18.0%</p>
               </td>
               <td>
                  <p>15.5%</p>
               </td>
               <td>
                  <p>14.5%</p>
               </td>
               <td>
                  <p>14.0%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>3rd</p>
               </td>
               <td>
                  <p>23.0%</p>
               </td>
               <td>
                  <p>21.0%</p>
               </td>
               <td>
                  <p>18.0%</p>
               </td>
               <td>
                  <p>16.0%</p>
               </td>
               <td>
                  <p>15.0%</p>
               </td>
               <td>
                  <p>13.5%</p>
               </td>
               <td>
                  <p>12.5%</p>
               </td>
               <td>
                  <p>11.0%</p>
               </td>
               <td>
                  <p>11.0%</p>
               </td>
               <td>
                  <p>10.5%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>4th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>9.0%</p>
               </td>
               <td>
                  <p>13.0%</p>
               </td>
               <td>
                  <p>12.0%</p>
               </td>
               <td>
                  <p>10.5%</p>
               </td>
               <td>
                  <p>10.0%</p>
               </td>
               <td>
                  <p>8.5%</p>
               </td>
               <td>
                  <p>9.0%</p>
               </td>
               <td>
                  <p>9.0%</p>
               </td>
               <td>
                  <p>9.0%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>5th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>8.0%</p>
               </td>
               <td>
                  <p>10.0%</p>
               </td>
               <td>
                  <p>9.0%</p>
               </td>
               <td>
                  <p>8.0%</p>
               </td>
               <td>
                  <p>7.5%</p>
               </td>
               <td>
                  <p>8.0%</p>
               </td>
               <td>
                  <p>8.0%</p>
               </td>
               <td>
                  <p>8.0%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>6th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>7.5%</p>
               </td>
               <td>
                  <p>6.5%</p>
               </td>
               <td>
                  <p>6.0%</p>
               </td>
               <td>
                  <p>6.0%</p>
               </td>
               <td>
                  <p>7.0%</p>
               </td>
               <td>
                  <p>7.0%</p>
               </td>
               <td>
                  <p>6.5%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>7th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>5.0%</p>
               </td>
               <td>
                  <p>5.0%</p>
               </td>
               <td>
                  <p>5.5%</p>
               </td>
               <td>
                  <p>5.5%</p>
               </td>
               <td>
                  <p>5.5%</p>
               </td>
               <td>
                  <p>5.5%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>8th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>4.0%</p>
               </td>
               <td>
                  <p>4.5%</p>
               </td>
               <td>
                  <p>5.0%</p>
               </td>
               <td>
                  <p>5.0%</p>
               </td>
               <td>
                  <p>5.0%</p>
               </td>
               <td>
                  <p>5.0%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>9th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>4.0%</p>
               </td>
               <td>
                  <p>4.0%</p>
               </td>
               <td>
                  <p>4.5%</p>
               </td>
               <td>
                  <p>4.5%</p>
               </td>
               <td>
                  <p>4.5%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>10th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>3.5%</p>
               </td>
               <td>
                  <p>4.0%</p>
               </td>
               <td>
                  <p>4.0%</p>
               </td>
               <td>
                  <p>4.0%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>11th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>3.5%</p>
               </td>
               <td>
                  <p>3.5%</p>
               </td>
               <td>
                  <p>3.5%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>12th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>3.0%</p>
               </td>
               <td>
                  <p>3.0%</p>
               </td>
            </tr>
            <tr>
               <td>
                  <p>13th</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>&nbsp;</p>
               </td>
               <td>
                  <p>2.5%</p>
               </td>
            </tr>
         </tbody>
      </table>
      <p>Tentative Payout Schedule. Subject to change at any time.</p>
    </div>
  </div>
  <?php
  include '../components/divider.php';
  include '../components/footer.php'; 
  ?>

</body>

</html>
